on:
  issues:
    types: [labeled]
jobs:
  Move_Labeled_Issue_On_Project_Board:
    runs-on: ubuntu-latest
    steps:
    - uses: konradpabjan/move-labeled-or-milestoned-issue@v2.0
      with:
        action-token: "${{ secrets.ROADMAP_TOKEN }}"
        project-url: "https://github.com/usesql/roadmap/projects/1"
        column-name: "Approved Features"
        label-name: "Approved"
        columns-to-ignore: "Approved Features,In Progress,Released"
